import type { Metadata } from "next";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.css';  // Import FontAwesome CSS


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
